services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

test_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: recipe_test_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
